#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Inline the hardware runtime into one standalone file per Asahi workload."""

import ast
from pathlib import Path


SOURCE = Path(__file__).with_name("asahi.py")
COMMON = {
    "U16", "GPU_PAGE", "BARRIER_NONE", "TRACE", "record", "Version", "Params",
    "GetParams", "VMCreate", "VMDestroy", "BindOp", "VMBind", "GEMCreate",
    "MmapOffset", "QueueCreate", "QueueDestroy", "Sync", "Submit", "GEMClose",
    "SyncCreate", "SyncDestroy", "SyncWait", "IOCTLS", "trace", "require",
    "ioc", "commands", "load_workload", "mapped", "validate_workload", "Device", "main",
}
COMPUTE = {"SHADER_PREFIX", "ARITHMETIC", "SHADER_SUFFIX", "usc_uniform", "build_compute"}
RENDER = {"Helper", "ZLSBuffer", "BgEot", "Timestamp", "Timestamps", "Render",
          "build_render", "FIXTURES"}


def generate(operation):
    source = SOURCE.read_text()
    lines = source.splitlines(keepends=True)
    tree = ast.parse(source)
    selected = COMMON | (RENDER if operation == "tri" else COMPUTE)
    if operation != "tri":
        selected -= {"BARRIER_NONE", "load_workload"}
    original_doc = ast.get_docstring(tree)
    license_text = original_doc[original_doc.index("Embedded Mesa helper shaders:"):]
    description = ("8x8 full-viewport red triangle" if operation == "tri" else
                   f"four-element float32 {operation.upper()}")
    mechanism = ("The native render state is embedded; the DRM render payload uses named fields."
                 if operation == "tri" else
                 "Shader bytes, uniform bindings, USC pipeline and CDM launch are explicit below.")
    doc = f'''"""Standalone M1 Asahi DRM {description}.

    python3 {operation}_asahi.py
    python3 {operation}_asahi.py --dry-run
    AGX_TRACE=2 python3 {operation}_asahi.py

Python standard library only. Opens the Asahi render node, creates a VM and
GEM buffers, binds GPU addresses, submits and waits for a completion fence.
{mechanism}
Hardware validated on M1 G13G B1. No repo imports or graphics APIs at runtime.
--dry-run only prepares data; PASS requires the GPU output to match.

{license_text}
"""'''
    parts = ["#!/usr/bin/env python3\n# SPDX-License-Identifier: MIT\n", doc,
             "\n# Generated by experimental/asahi2standalone.py; runtime is self-contained.\n"]
    for node in tree.body[1:]:
        if isinstance(node, (ast.Import, ast.ImportFrom)):
            module = node.names[0].name if isinstance(node, ast.Import) else node.module
            if operation != "tri" and module in ("base64", "hashlib", "json", "zlib"):
                continue
            name = None
        elif isinstance(node, ast.Assign):
            target = node.targets[0]
            name = target.id if isinstance(target, ast.Name) else target.elts[0].id
        elif isinstance(node, (ast.FunctionDef, ast.ClassDef)):
            name = node.name
        elif isinstance(node, ast.If):
            name = None  # __main__ guard
        else:
            continue
        if name is not None and name not in selected:
            continue
        start = node.lineno - 1
        while start > 0 and lines[start-1].lstrip().startswith("#"):
            start -= 1
        blank_lines = 0
        while start - blank_lines > 0 and not lines[start - blank_lines - 1].strip():
            blank_lines += 1
        text = "".join(lines[start:node.end_lineno])
        if name == "load_workload":
            text = text.replace('    if name in ("add", "mul"):\n        return build_compute(name)\n', "")
        elif name == "validate_workload":
            first = text.index('\n        if kind == 1:')
            second = text.index('\n        else:', first)
            end = text.index('\n    require(hardware_count', second)
            if operation == "tri":
                text = text[:first] + "\n" + "\n".join(
                    line[4:] for line in text[second:end].splitlines()[2:]) + text[end:]
                first = text.index('\n    if name in ("add", "mul"):')
                second = text.index('\n    else:', first)
                text = text[:first] + "\n" + "\n".join(
                    line[4:] for line in text[second:].splitlines()[2:]) + "\n"
            else:
                text = text[:first] + "\n" + "\n".join(
                    line[4:] for line in text[first:second].splitlines()[2:]) + text[end:]
                text = text[:text.index('\n    else:\n        # The captured EOT')]
                first = text.index('\n        require(kind in')
                second = text.index('\n        hardware_count += 1', first)
                text = text[:first] + '\n        require(kind == 1, "expected a compute command")' + text[second:]
        elif name == "Device":
            first = text.index('\n        if name in ("add", "mul"):')
            second = text.index('\n        pixels =', first)
            if operation == "tri":
                text = text[:first] + text[second:]
            else:
                text = text[:first] + "\n" + "\n".join(
                    line[4:] for line in text[first:second].splitlines()[2:]) + "\n"
                text = text.replace('        if name == "tri":\n            require(p.max_attachments >= 1, "device cannot accept a render attachment")\n', "")
        elif name == "ARITHMETIC":
            instruction = next(line for line in text.splitlines()
                               if line.lstrip().startswith(f'"{operation}"'))
            text = "ARITHMETIC = {\n" + instruction + "\n}"
        elif name == "FIXTURES":
            text = text.replace(" on 2026-10-05. ADD/MUL use the\n# explicit shader and USC/CDM constructors above and do not load this blob.",
                                " on 2026-10-05.")
        elif name == "main":
            text = text.replace('    parser.add_argument("workload", nargs="?", default="all", choices=("add", "mul", "tri", "all"))\n', "")
            first = text.index('\n    workloads =')
            second = text.index('\n    return 0', first)
            body = text[first:second].splitlines()[3:]
            text = text[:first] + f'\n    name = "{operation}"\n' + "\n".join(
                line[4:] for line in body) + text[second:]
            text = text.replace("        continue", "        return 0")
            if operation != "tri":
                text = text.replace("load_workload(name)", "build_compute(name)")
        elif isinstance(node, ast.If) and operation != "tri":
            text = text.replace(", zlib.error", "")
        parts.extend(("\n" * min(blank_lines, 2), text.rstrip(), "\n"))
    output = "".join(parts).rstrip() + "\n"
    ast.parse(output)
    destination = SOURCE.parent.parent / "examples" / f"{operation}_asahi.py"
    destination.write_text(output)
    print(f"{destination}: {len(output.splitlines())} lines, no repo imports")


if __name__ == "__main__":
    for operation in ("add", "mul", "tri"):
        generate(operation)
